# Generated by Django 5.0.4 on 2024-04-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(max_length=255)),
                ('con_email', models.EmailField(max_length=255)),
                ('con_message', models.TextField()),
            ],
        ),
    ]
