# Generated by Django 5.0.4 on 2024-04-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='reg_phnumber',
            new_name='reg_phnum',
        ),
    ]
