# Generated by Django 5.0.4 on 2024-05-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pro_size',
            new_name='pro_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pro_message',
        ),
        migrations.AddField(
            model_name='product',
            name='pro_image',
            field=models.FileField(null=True, upload_to='pro'),
        ),
    ]
