# Generated by Django 5.0.3 on 2024-05-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catergary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=255)),
                ('cate_image', models.FileField(null=True, upload_to='catergory')),
            ],
        ),
    ]
