# Generated by Django 5.0.3 on 2024-05-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_catergary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergary',
            name='cate_image',
            field=models.FileField(null=True, upload_to='cate'),
        ),
    ]
