# Generated by Django 5.0.3 on 2024-05-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_catergary_cate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergary',
            name='cate_image',
            field=models.FileField(null=True, upload_to='catee'),
        ),
    ]
