# Generated by Django 5.0.3 on 2024-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_catergary_cate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='procat_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
