# Generated by Django 5.0.6 on 2024-06-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_message', models.TextField()),
                ('noti_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_user', models.CharField(default=None, max_length=250)),
                ('wish_proid', models.IntegerField(null=True)),
                ('wish_name', models.CharField(max_length=250)),
                ('wish_price', models.FloatField(max_length=250)),
                ('wish_image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
