# Generated by Django 5.0.6 on 2024-06-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_notification_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wish_user',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
