# Generated by Django 5.0.6 on 2024-07-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_wishlist_wish_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reg_img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
