# Generated by Django 5.0.6 on 2024-07-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_registration_reg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='reg_img',
            field=models.FileField(null=True, upload_to='profile'),
        ),
    ]
