# Generated by Django 5.0.6 on 2024-07-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_registration_reg_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reg_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
