# Generated by Django 5.0.6 on 2024-07-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_registration_reg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='noty_user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
