# Generated by Django 5.0.6 on 2024-07-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_notification_noty_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noti_date',
            field=models.DateTimeField(null=True),
        ),
    ]
