# Generated by Django 5.0.6 on 2024-08-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_notification_noti_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dash_password', models.CharField(max_length=255)),
                ('dash_username', models.CharField(max_length=255)),
            ],
        ),
    ]
